package za.co.entelect.challenge.command.groups;
import za.co.entelect.challenge.command.Command;
import za.co.entelect.challenge.entities.GameState;

import java.util.ArrayList;

// An interface to a command group.
// It should have update and get commands.
public interface CommandGroups {

    // Update the group, generate the proper commands
    // given the current game state, then save it in
    // commands.
    public void update(GameState state);

    // Get the commands generated by this group.
    // Should be called after update.
    public ArrayList<Command> getCommands();
}
